---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Import vars for WireGuard
  ansible.builtin.import_tasks: import-vars.yml

- name: Install WireGuard
  ansible.builtin.import_tasks: install-wireguard.yml

- name: Configure WireGuard 
  ansible.builtin.import_tasks: setup-wireguard.yml
